<?php
$this->title = "My Albums";
$this->headTitle($this->title);
?>
<table class="table table-hover">
    <tr>
        <th>Title</th>
        <th>Artist</th>
        <th>&nbsp;</th>
    </tr>
    <?php foreach($this->albums as $album) : ?>
        <tr>
            <td><?php echo $this->escape($album->title);?></td>
            <td><?php echo $this->escape($album->artist);?></td>
            <td>
                <a href="<?php echo $this->url(array('controller'=>'index','action'=>'edit', 'id'=>$album->id));?>">Edit</a>
                <a href="<?php echo $this->url(array('controller'=>'index','action'=>'delete', 'id'=>$album->id));?>">Delete</a>
            </td>
        </tr>
    <?php endforeach; ?>
</table>
