<?php
$this->title = 'Editora - Imprimir';
$this->headTitle($this->title);
?>
    <div class="navbar">
        <div class="navbar-inner">
            <ul class="nav menu-forms">
                <li><a href="<?php echo $this->url(array('controller' => 'bl-editoras','action' => 'grid',)); ?>"><button class="btn">Voltar <i class="icon-circle-arrow-left"></i></button></a></li>
            </ul>
        </div>
    </div>
    <fieldset>
        <legend>Impress&atilde;o Editora</legend>
        <br />
        N&atilde;o h&aacute; dados para a impress&atilde;o.
    </fieldset>
