<?php
$this->title = 'Editoras - Listagem';
$this->headTitle($this->title);
?>
<?php if(!empty($this->editoras)) : ?>
    <h2>Listagem de Editoras Cadastradas</h2>
    <div class="navbar">
      <div class="navbar-inner">
        <ul class="nav menu-forms">
            <li><a href="<?php echo $this->url(array('controller' => 'bl-editoras','action' => 'cadastrar'));?>"><button class="btn">Novo <i class="icon-file"></i></button></a></li>
            <li><a href="<?php echo $this->url(array('controller' => 'bl-editoras','action' => 'imprimir'));?>"><button class="btn">Imprimir pdf <i class="icon-print"></i></button></a></li>
            <li><a href="<?php echo $this->url(array('controller' => 'bl-editoras','action' => 'exportar'));?>"><button class="btn">Exportar xsl <i class="icon-download-alt"></i></button></a></li>
        </ul>
      </div>
    </div>
    <?php if (count($this->menssagens)) : ?>
        <?php foreach ($this->menssagens as $menssagens) : ?>
            <div class="alert alert-success">
                <button type="button" class="close" data-dismiss="alert"><i class=" icon-remove"></i></button>
                <?php echo $this->escape($menssagens); ?>
            </div>
        <?php endforeach; ?>
    <?php endif; ?>
    <table class="table table-hover">
        <tr>
            <th>Nome</th>
            <th>Endere&ccedil;o</th>
            <th>Observa&ccedil;&atilde;o</th>
            <th>A&ccedil;&otilde;es</th>
        </tr>
        <?php foreach ($this->editoras as $editora) : ?>
            <tr>
                <td><?php echo $this->escape($editora->desc_nome); ?></td>
                <td><?php echo $this->escape($editora->desc_endereco); ?></td>
                <td><?php echo $this->escape($editora->desc_observacoes); ?></td>
                <td>
                    <a href="<?php echo $this->url(array('controller' => 'bl-editoras','action' => 'editar', 'numg_editora' => $editora->numg_editora));?>"><button class="btn">Editar <i class="icon-edit"></i></button></a>
                    <a href="<?php echo $this->url(array('controller' => 'bl-editoras','action' => 'deletar', 'numg_editora' => $editora->numg_editora));?>"><button class="btn">Deletar <i class="icon-trash"></i></button></a>
                </td>
            </tr>
        <?php endforeach; ?>
    </table>
<?php else : ?>
     <fieldset>
        <legend>Cadastro de Editoras</legend><br />
        <div class="alert alert-error">
            <button type="button" class="close" data-dismiss="alert"><i class=" icon-remove"></i></button>
            <h4>N&atilde;o h&aacute; Editoras cadastradas at&eacute; o momento.</h4><br/>
            Para iniciar o cadastro, clique no bot&atilde;o abaixo.&nbsp;&nbsp;<i class="icon-hand-down"></i>
        </div>
        <p><a class="btn btn-large btn-block" type="button" href="<?php echo $this->url(array('controller'=>'bl-editoras','action'=>'cadastrar'));?>">Cadastrar</a></p>
     </fieldset>
<?php endif;?>